Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -40,7 +40,13 @@ jobs:
     
     - name: Docker stats
       run: docker stats --no-stream
-
+      
+    # Debug directorios y propietarios
+    - name: Debug directory structure before tests
+      run: |
+        docker compose -f docker-compose.yml -f docker-compose.ci.yml exec web ls -lra /app
+        docker compose -f docker-compose.yml -f docker-compose.ci.yml exec web ls -lra /app/coveragereport || echo "coveragereport not found"
+        
     # Ejecutamos los test en el contenedor Django
     - name: Run Django tests
       run: docker compose run --rm web coverage run --rcfile=.github/workflows/.coveragerc manage.py test
